### ISSUE TITLE
DD4t.ContelModel.Page.LastPublishedDate not correct

### ISSUE THREAD

**Issue by LitikaChib** [dd4t/dd4t-2-model#22]
Hi, In my DD4T MVC Application, while rendering a page through "ActionExecutedContext" method, in my DD4T.ContentModel.Page i am getting value of "LastPublishedDate" as "01/01/0001". When i see in my Broker Database and check for the "Last_Published_Date" key for that particular page, i get correct date. Can anyone help me resolve the issue.

**Comment by quirijnslings** [comment]
You need to add this to the Web.config:

<add key="DD4T.IncludeLastPublishedDate" value="true" />
